/*
    날짜 : 2025/07/18
    이름 : 이다은
    내용 : SQL 연습문제1
*/

--실습 1-1
ALTER SESSION SET "_ORACLE_SCRIPT"=true;
create user shop identified by 1234;
grant connect, resource, unlimited tablespace to shop;

--실습 1-2

create table customer (
    CID NVARCHAR2(20) PRIMARY KEY,
    name NVARCHAR2(20) NOT NULL,
    hp CHAR(13) DEFAULT NULL,
    address VARCHAR2(200) DEFAULT NULL,
    RDATE DATE NOT NULL
);

create table product(
    pno NUMBER(4) PRIMARY KEY,
    pname NVARCHAR2(30) NOT NULL,
    stock NUMBER DEFAULT 0,
    price NUMBER,
    company CHAR(20) NOT NULL
);
create table orders(
    ORD_NO NUMBER generated by default as IDENTITY PRIMARY KEY,
    ORD_CID NVARCHAR2(20) NOT NULL,
    ORD_PNO NUMBER(4) NOT NULL,
    ORD_CNT NUMBER DEFAULT 1,
    ORD_DATE DATE NOT NULL
);
--실습 1-3
insert into customer values('c101', '김유신', '010-1234-1001', '김해시 봉황동', '2022-01-01');
insert into customer values('c102', '김춘추', '010-1234-1002', '경주시 보문동', '2022-01-02');
insert into customer values('c103', '장보고', '010-1234-1003', '완도군 청산면', '2022-01-03');
insert into customer values('c104', '강감찬', '010-1234-1004', '서울시 마포구', '2022-01-04');
insert into customer (cid, name, rdate) values('c105', '이성계', '2022-01-05');
insert into customer values('c106', '정철', '010-1234-1006', '경기도 용인시', '2022-01-06');
insert into customer (cid, name, rdate) values('c107', '허준', '2022-01-07');
insert into customer values('c108', '이순신', '010-1234-1008', '서울시 영등포구', '2022-01-08');
insert into customer values('c109', '송상현', '010-1234-1009', '부산시 동래구', '2022-01-09');
insert into customer values('c110', '정약용', '010-1234-1010', '경기도 광주시', '2022-01-10');

insert into product values(1, '새우깡', 5000, 1500, '농심');
insert into product values(2, '초코파이', 2500, 2500, '오리온');
insert into product values(3, '포카칩', 3600, 1700, '오리온');
insert into product values(4, '양파링', 1250, 1800, '농심');
insert into product (pno, pname, stock, company) values(5, '죠리퐁', 2200, '크라운');
insert into product values(6, '마가렛트', 3500, 3500, '롯데');
insert into product values(7, '뿌셔뿌셔', 1650, 1200, '오뚜기');

insert into orders values(1, 'c102', 3, 2, '2022-07-01 13:15:10');
insert into orders values(2, 'c101', 4, 1, '2022-07-01 14:16:11');
insert into orders values(3, 'c108', 1, 1, '2022-07-01 17:23:18');
insert into orders values(4, 'c109', 6, 5, '2022-07-02 10:46:36');
insert into orders values(5, 'c102', 2, 1, '2022-07-03 09:15:37');
insert into orders values(6, 'c101', 7, 3, '2022-07-03 12:35:12');
insert into orders values(7, 'c110', 1, 2, '2022-07-03 16:55:36');
insert into orders values(8, 'c104', 2, 4, '2022-07-04 14:23:23');
insert into orders values(9, 'c102', 1, 3, '2022-07-04 21:54:34');
insert into orders values(10, 'c107', 6, 1, '2022-07-05 14:21:03');
--실습 1-4
select * from customer;

--실습 1-5
select cid, name, hp from customer;

--실습 1-6
select * from product;

--실습 1-7
select company from product;

--실습 1-8 **
select DISTINCT company from product; 

--실습 1-9
select pname, price from product;

--실습 1-10 **
SELECT PNAME, PRICE+500 AS 조정단가 FROM PRODUCT;

--실습 1-11
select pname, stock, price from product where company='오리온';

--실습 1-12
select ord_pno, ord_cnt, ord_date FROM orders WHERE ord_cid='c102';

--실습 1-13
select ord_pno, ord_cnt, ord_date FROM orders 
WHERE ord_cid='c102' AND ord_cnt>=2;

--실습 1-14
select * FROM product WHERE price>=1000 AND price<=2000;

--실습 1-15 **
select cid, name, hp, address FROM customer WHERE name like '김%';

--실습 1-16 **
select cid, name, hp, address FROM customer WHERE name like '__';

--실습 1-17 **
select * from customer where hp is null;

--실습 1-18
select * from customer WHERE address IS NOT NULL;

--실습 1-19
SELECT * FROM CUSTOMER ORDER BY RDATE DESC;

--실습 1-20 **
SELECT * FROM orders WHERE ORD_CNT>=3 
ORDER BY ORD_CNT DESC, ORD_PNO ASC;

--실습 1-21
SELECT AVG(PRICE) FROM PRODUCT;

--실습 1-22
SELECT SUM(STOCK) AS "재고량 합계" FROM PRODUCT WHERE COMPANY='농심';

--실습 1-23 **
SELECT COUNT(*) AS 고객수 FROM CUSTOMER;

--실습 1-24
SELECT COUNT(DISTINCT COMPANY) AS "제조업체 수" FROM PRODUCT; 

--실습 1-25 **
SELECT 
    ORD_PNO as "주문 상품번호", 
    SUM(ORD_CNT) as "총 주문수량" 
FROM ORDERS 
GROUP BY ORD_PNO 
ORDER BY ORD_PNO ASC;

--실습 1-26
SELECT company AS 제조업체, COUNT(*) AS 제품수, MAX(price) AS 최고가 FROM product
group by company order by company ASC;

--실습 1-27 **
SELECT 
    COMPANY AS 제조업체, 
    COUNT(*) AS 제품수, 
    MAX(price) AS 최고가 
FROM PRODUCT 
GROUP BY COMPANY 
HAVING COUNT(*)>=2;

--실습 1-28
SELECT ORD_PNO, ORD_CID, sum(ORD_CNT) AS "총 주문수량" 
    FROM ORDERS
    group by ord_pno, ord_cid
    order by ord_pno asc;

--실습 1-29
SELECT ORD_CID, PNAME FROM ORDERS a
join product p on a.ord_pno = p.pno
WHERE ORD_CID = 'c102';

--실습 1-30
select ord_cid, name, pname, ord_date 
from orders a
join customer b on a.ord_cid = b.cid
join product c on a.ord_pno = c.pno
where substr(ord_date, 1, 10) = '2022-07-03';
--where ord_date like '2022-07-03%';


--몰랐던 부분들 복습하기!!
--실습 8

--실습 10

--실습 15

--실습 16

--실습 17

--실습 20

--실습 23

--실습 25

--실습 27

--실습 28

--실습 29

--실습 30